### ISSUE TITLE
Hotkey still requires one to choose the workflow

### ISSUE THREAD

**Issue by simonleandergrimm** [giovannicoppola/alfred-complice#2]
I assigned a hotkey to launch the Complice workflow, but I'm still required to press enter to launch the workflow itself. Could this be automated? It's minor, but that kind of friction leads me not to use some feature.

**Comment by giovannicoppola** [comment]
no, Alfred's hotkeys don't require pressing enter. What is the hotkey? keep in mind that hotkeys work without launching Alfred first, so they need to be unique and not conflict with other system- or application-specific keyboard shortcuts
