### ISSUE TITLE
Workflow not showing options to choose from, thus not working properly.

### ISSUE THREAD

**Issue by simonleandergrimm** [giovannicoppola/alfred-complice#3]
Hi,

When starting the workflow, I am not shown any options to choose from. I've added a recording of me using the workflow, using both a hotkey and '!c'.

I've completely reinstalled both Alfred and alfred-complice, and added my Complice token (without quotes), but still get this result.

I've also tried a keyword for 'New Intention', but wasn't able to use it then as well.

Would you know others who have the same issue?

https://user-images.githubusercontent.com/58591538/170884875-9286625c-4e37-4b5f-aa43-0dc300942856.mov

**Comment by giovannicoppola** [comment]
@simonleandergrimm were you able to get it to work?

**Comment by simonleandergrimm** [comment]
Yep, mistake on my part.
